// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ava-upsell/BookedCalendarHero.tsx": () => import("../components/mockups/ava-upsell/BookedCalendarHero.tsx"),
  "./components/mockups/ava-upsell/BookingConfirmedHero.tsx": () => import("../components/mockups/ava-upsell/BookingConfirmedHero.tsx"),
  "./components/mockups/ava-upsell/CalendarIllustration.tsx": () => import("../components/mockups/ava-upsell/CalendarIllustration.tsx"),
  "./components/mockups/ava-upsell/Current.tsx": () => import("../components/mockups/ava-upsell/Current.tsx"),
  "./components/mockups/ava-upsell/LifestyleHero.tsx": () => import("../components/mockups/ava-upsell/LifestyleHero.tsx"),
  "./components/mockups/ava-upsell/ServicePro.tsx": () => import("../components/mockups/ava-upsell/ServicePro.tsx"),
  "./components/mockups/ava-upsell/TapToBookHero.tsx": () => import("../components/mockups/ava-upsell/TapToBookHero.tsx"),
  "./components/mockups/empty-illus/BookedHour.tsx": () => import("../components/mockups/empty-illus/BookedHour.tsx"),
  "./components/mockups/empty-illus/CalendarMark.tsx": () => import("../components/mockups/empty-illus/CalendarMark.tsx"),
  "./components/mockups/empty-illus/CalendarMarkGreen.tsx": () => import("../components/mockups/empty-illus/CalendarMarkGreen.tsx"),
  "./components/mockups/empty-illus/CalendarMarkOrange.tsx": () => import("../components/mockups/empty-illus/CalendarMarkOrange.tsx"),
  "./components/mockups/empty-illus/CalendarMarkSoft.tsx": () => import("../components/mockups/empty-illus/CalendarMarkSoft.tsx"),
  "./components/mockups/empty-illus/CalendarsSynced.tsx": () => import("../components/mockups/empty-illus/CalendarsSynced.tsx"),
  "./components/mockups/empty-illus/OpenBooking.tsx": () => import("../components/mockups/empty-illus/OpenBooking.tsx"),
  "./components/mockups/empty-illus/PhoneConfirm.tsx": () => import("../components/mockups/empty-illus/PhoneConfirm.tsx"),
  "./components/mockups/empty-illus/RecurringBooking.tsx": () => import("../components/mockups/empty-illus/RecurringBooking.tsx"),
  "./components/mockups/empty-illus/ShareLink.tsx": () => import("../components/mockups/empty-illus/ShareLink.tsx"),
  "./components/mockups/empty-illus/TapToBook.tsx": () => import("../components/mockups/empty-illus/TapToBook.tsx"),
  "./components/mockups/empty-illus/TimeSlots.tsx": () => import("../components/mockups/empty-illus/TimeSlots.tsx")
};
