module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "aiaccent-2": "var(--aiaccent-2)",
        sui: {
          cobranding: "var(--sui-colors-cobranding)",
          "cobranding-t10": "var(--sui-colors-cobranding-t10)",
          "cobranding-t20": "var(--sui-colors-cobranding-t20)",
          "cobranding-on": "var(--sui-colors-cobranding-on-default)",
          "neutral-base": "var(--sui-colors-neutral-base)",
          "neutral-w0": "var(--sui-colors-neutral-w0)",
          "neutral-b0": "var(--sui-colors-neutral-b0)",
          "neutral-b0-t10": "var(--sui-colors-neutral-b0-t10)",
          "neutral-b0-t20": "var(--sui-colors-neutral-b0-t20)",
          "neutral-b1": "var(--sui-colors-neutral-b1)",
          "neutral-b2": "var(--sui-colors-neutral-b2)",
          "neutral-b3": "var(--sui-colors-neutral-b3)",
          "neutral-b4": "var(--sui-colors-neutral-b4)",
          "neutral-b4-t50": "var(--sui-colors-neutral-b4-t50)",
          "neutral-b5": "var(--sui-colors-neutral-b5)",
          success: "var(--sui-colors-success)",
          danger: "var(--sui-colors-danger)",
          warning: "var(--sui-colors-warning)",
          "ai-accent-2": "var(--sui-colors-ai-accent-2)",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "caption2-UPPER": "var(--caption2-UPPER-font-family)",
        descriptor: "var(--descriptor-font-family)",
        "descriptor-mini": "var(--descriptor-mini-font-family)",
        "detail-bold": "var(--detail-bold-font-family)",
        "display-2": "var(--display-2-font-family)",
        headline: "var(--headline-font-family)",
        "main-text": "var(--main-text-font-family)",
        "mobile-detailbold": "var(--mobile-detailbold-font-family)",
        subtitle: "var(--subtitle-font-family)",
        "subtitle-mini": "var(--subtitle-mini-font-family)",
        title: "var(--title-font-family)",
        "title-2": "var(--title-2-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { "boxshadow-md": "var(--boxshadow-md)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
